apiVersion: v1
kind: Service
metadata:
  name: content-risk-scoring
  namespace: content-risk-staging
spec:
  selector:
    app: content-risk-scoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
